name = "@_LOWER:NAME_@"
description = "@_DESCRIPTION_@"
version = "0.1.0-dev"

authors = ["@_USERNAME_@"]
maintainers = ["@_USERNAME_@ <@_EMAIL_@>"]
maintainers-logins = ["@_LOGIN_@"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = "@_WEBSITE_@"
tags = [@_TAGS_@]

@_TEST_@
