name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup upterm session
      uses: mxschmitt/action-tmate@v3
