name: CI Test

on:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - '**.rst'
      - '**.txt'
  release:
    types: [published]
  workflow_dispatch:

env:
  ALIRE_OS:     windows
  MSYS64_ROOT:  C:\Users\runneradmin\AppData\Local\alire\cache\msys64
  MINGW64_PATH: C:\Users\runneradmin\AppData\Local\alire\cache\msys64\mingw64\bin
  MSYS2_PATH:   C:\Users\runneradmin\AppData\Local\alire\cache\msys64\usr\bin
  PACMAN:       C:\Users\runneradmin\AppData\Local\alire\cache\msys64\usr\bin\pacman --noconfirm

jobs:

  build:
    name: CI Test

    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Install FSF toolchain
      uses: alire-project/alr-install@v1
      with:
        crates: gnat_native gprbuild

    - name: Build alr
      run: gprbuild -j0 -p -P alr_env

    - name: Remove previous alr's msys2 (so a new one can be tested)
      shell: pwsh
      run: |
        if (Test-Path "${{env.MSYS64_ROOT}}") {
          Remove-Item "${{env.MSYS64_ROOT}}" -Recurse -Force }

    - name: Display built alr and trigger install of msys2
      run: ./bin/alr version

    - name: Display built alr (BASH)
      run: ./bin/alr version
      shell: bash

    - name: Display built alr (PATH)
      shell: bash
      run: |
        export PATH=$PATH:$PWD/bin
        alr version

    - name: Rename in preparation to upload artifact
      shell: bash
      run: |
        mv bin/alr.exe bin/alr-ok.exe

    - name: Checkout problematic commit and rebuild
      run: |
        git checkout 0ee09278
        gprbuild -j0 -p -P alr_env

    - name: Verify failure, rename, etc
      shell: bash
      run: |
        export PATH=$PATH:$PWD/bin
        alr version && echo ÉXITO TOTAL || \
        {
          echo "ERROR: alr version failed"
          mv bin/alr.exe bin/alr-fail.exe
          ls -alF bin
        }

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: alr
        path: bin