name: Release on Linux

on:
  push:
    tags:
      - 'v*' # version tags

jobs:

  build:
    name: build on ${{ matrix.tag }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        tag: # Those are our dockerhub alire/gnat:tag machines
            - centos-latest-community-latest
            - community-latest
            - debian-stable
            - ubuntu-lts

    steps:
    - name: Check out repository
      uses: actions/checkout@v1

    - name: Check out submodules
      run: git submodule update --init --recursive

    - name: Pull docker image
      run: docker pull alire/gnat:${{ matrix.tag }}

    - name: Build
      run: >
        docker run -v${PWD}:/alire -w /alire
        -e "BRANCH=${{ github.base_ref }}" -e "INDEX=${{ env.alire_index }}"
        alire/gnat:${{ matrix.tag }} gprbuild -j0 -p -P alr_env

    - name: Package binaries
      run: zip alr-bin-${{ matrix.tag }}.zip bin/alr LICENSE.txt

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

   - name: Upload binary assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: alr-bin-${{ matrix.tag }}.zip
        asset_name: alr-bin-${{ matrix.tag }}.zip
        asset_content_type: application/zip 
